### ISSUE TITLE
Hey friend! Your theme is great! What font is used for this theme?

### ISSUE THREAD

**Issue by zhouxinghong** [cnmorocho/min-gruvbox-theme#2]
Hey friend! Your theme is great! What font is used for this theme?

In addition, the theme cannot be installed in vscode 1.40.

**Comment by cnmorocho** [comment]
Thank you! The Font is [Monaspace (Neon)](https://monaspace.githubnext.com/), is the Github Font 🤓

> In addition, the theme cannot be installed in vscode 1.40.

About that, I think that version is from 2020 or like that right? I think that I'll not concern about that, and sorry if that affects you.
